### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by scytherswings**
Added `require` statement example to readme.

### CODE REVIEW

**Comment by nahiluhmot** [comment]
Thanks for the contribution @scytherswings! It's confusing (and probably not the best practice) that the gem's name doesn't match the `require` path. However, since `require` doesn't technically install the gem, the language isn't quite right. Maybe change it to something like:

> Then you can `require` it using:

**Comment by scytherswings** [comment]
@nahiluhmot Perhaps my latest change is more clear?

**Comment by nahiluhmot** [comment]
Great, thanks again @scytherswings.

**Comment by nahiluhmot** [comment]
Will merge after the travis build.

**Comment by scytherswings** [comment]
Awesome! Thanks! I hope that change will help other users, I felt really dumb for a while when I couldn't figure out how to `require` it haha.

**Comment by nahiluhmot** [comment]
Looks like the travis build is a bit stale. Since ruby 1.9.3 is past [end of life](https://www.ruby-lang.org/en/news/2014/01/10/ruby-1-9-3-will-end-on-2015/), I'm just going to merge this and deal with that later.

**Pull request merged**
